# Generated by Django 3.0.6 on 2020-05-25 17:43

from django.db import migrations, models
import text.validators


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0002_auto_20200525_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='file',
            field=models.FileField(default=1, upload_to='documents/%Y/%m/%d', validators=[text.validators.validate_file_extension]),
            preserve_default=False,
        ),
    ]
