# Generated by Django 3.0.6 on 2020-05-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('text', '0003_text_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='text',
            name='file',
            field=models.FileField(upload_to='images/'),
        ),
    ]
